import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/styles";
import { Banner } from "@repo/components";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Banner>
          <div>하이</div>
        </Banner>
        <div>{children}</div>
      </body>
    </html>
  );
}
